import React, { useState } from 'react';
import { useDashboard } from '../../context/DashboardContext';
import Header from '../../components/Header/Header';
import Filters from '../../components/Filters/Filters';
import BookingTable from '../../components/BookingTable/BookingTable';
import { FiPlus, FiX, FiCheckCircle, FiAlertCircle } from 'react-icons/fi';
import './Bookings.css';

const Bookings = () => {
  const { allBookings, addNewBooking } = useDashboard();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState('');
  
  // Form State
  const [formData, setFormData] = useState({
    guestName: '',
    age: '28',
    gender: 'Male',
    country: 'India',
    roomType: 'Single Room',
    roomNumber: '101',
    checkIn: '',
    checkOut: '',
    paymentMethod: 'Credit Card',
    revenue: '150'
  });

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const triggerEmailNotification = (booking) => {
    console.log(`[Email Service] Triggering reservation email to mirfurkaan106@gmail.com...`);
    
    const subject = encodeURIComponent(`[Panun Ghar] New Booking Alert: ${booking.BookingID} (${booking.GuestName})`);
    const body = encodeURIComponent(
      `Hello Mir Furqaan,\n\n` +
      `A new reservation has been successfully booked at Panun Ghar:\n\n` +
      `- Booking ID: ${booking.BookingID}\n` +
      `- Guest Name: ${booking.GuestName} (${booking.Age} y/o, ${booking.Gender})\n` +
      `- Origin Country: ${booking.Country}\n` +
      `- Room Reserved: ${booking.RoomType} (Room ${booking.RoomNumber})\n` +
      `- Stay Dates: ${booking.CheckIn} to ${booking.CheckOut}\n` +
      `- Payment Details: ${booking.PaymentMethod} ($${booking.Revenue})\n` +
      `- Booking Status: Confirmed\n\n` +
      `This message was automatically generated by the Panun Ghar dashboard.\n` +
      `System Email Destination: mirfurkaan106@gmail.com`
    );
    
    // Trigger native mail app prefilled details
    const mailtoUrl = `mailto:mirfurkaan106@gmail.com?subject=${subject}&body=${body}`;
    window.location.href = mailtoUrl;
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    // Generate unique Booking ID
    const nextNum = allBookings.length + 1001;
    const newBookingId = `HB-${nextNum}`;

    const newBooking = {
      BookingID: newBookingId,
      GuestName: formData.guestName,
      Age: parseInt(formData.age),
      Gender: formData.gender,
      Country: formData.country,
      HotelName: 'Panun Ghar',
      RoomType: formData.roomType,
      RoomNumber: parseInt(formData.roomNumber),
      BookingDate: new Date().toISOString().split('T')[0],
      CheckIn: formData.checkIn,
      CheckOut: formData.checkOut,
      BookingSource: 'Direct',
      PaymentMethod: formData.paymentMethod,
      BookingStatus: 'Confirmed',
      PaymentStatus: 'Paid',
      Revenue: parseInt(formData.revenue),
      Rating: null
    };

    // Update global state
    addNewBooking(newBooking);

    // Close Modal
    setIsModalOpen(false);

    // Show toast message
    setToastMessage(`Booking ${newBookingId} created! Preparing email notification...`);
    setTimeout(() => setToastMessage(''), 4000);

    // Trigger Mailto prefilled details launch
    setTimeout(() => {
      triggerEmailNotification(newBooking);
    }, 1200);

    // Reset Form
    setFormData({
      guestName: '',
      age: '28',
      gender: 'Male',
      country: 'India',
      roomType: 'Single Room',
      roomNumber: '101',
      checkIn: '',
      checkOut: '',
      paymentMethod: 'Credit Card',
      revenue: '150'
    });
  };

  return (
    <div className="bookings-page page-container animate-fade-in">
      <Header 
        title="Bookings Registry" 
        subtitle="Manage hotel reservations, record new check-ins, and inspect database outputs"
      />
      
      {toastMessage && (
        <div className="toast-notification animate-fade-in">
          <FiCheckCircle size={16} />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Registry Top Banner Actions */}
      <div className="bookings-actions-banner card glass-panel">
        <div className="banner-left">
          <h3>Reservations Registry</h3>
          <p>Add new walk-in clients, send email updates, and track stays</p>
        </div>
        <button className="create-booking-btn" onClick={() => setIsModalOpen(true)}>
          <FiPlus size={18} />
          <span>Create New Booking</span>
        </button>
      </div>

      {/* Search and filter controls */}
      <Filters />

      {/* Main Registry Table */}
      <BookingTable />

      {/* Create Booking Overlay Modal */}
      {isModalOpen && (
        <div className="modal-backdrop">
          <div className="booking-modal card glass-panel animate-fade-in">
            <div className="modal-header">
              <h3>Create Reservation</h3>
              <button className="close-modal-btn" onClick={() => setIsModalOpen(false)}>
                <FiX size={20} />
              </button>
            </div>

            <form onSubmit={handleSubmit} className="booking-form">
              <div className="form-group-row">
                <div className="form-group">
                  <label>Guest Full Name</label>
                  <input 
                    type="text" 
                    name="guestName"
                    value={formData.guestName}
                    onChange={handleInputChange}
                    placeholder="e.g. Rohan Bhat"
                    required
                  />
                </div>
                <div className="form-group-sub">
                  <div className="form-group small">
                    <label>Age</label>
                    <input 
                      type="number" 
                      name="age"
                      value={formData.age}
                      onChange={handleInputChange}
                      min={18}
                      max={90}
                      required
                    />
                  </div>
                  <div className="form-group select-group">
                    <label>Gender</label>
                    <select name="gender" value={formData.gender} onChange={handleInputChange}>
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                      <option value="Non-binary">Non-binary</option>
                    </select>
                  </div>
                </div>
              </div>

              <div className="form-group-row">
                <div className="form-group">
                  <label>Origin Country</label>
                  <input 
                    type="text" 
                    name="country"
                    value={formData.country}
                    onChange={handleInputChange}
                    placeholder="e.g. India"
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Room Category</label>
                  <select name="roomType" value={formData.roomType} onChange={handleInputChange}>
                    <option value="Single Room">Single Room ($90/N)</option>
                    <option value="Double Room">Double Room ($140/N)</option>
                    <option value="Deluxe Suite">Deluxe Suite ($240/N)</option>
                    <option value="President Suite">President Suite ($550/N)</option>
                  </select>
                </div>
              </div>

              <div className="form-group-row">
                <div className="form-group">
                  <label>Room Number</label>
                  <input 
                    type="number" 
                    name="roomNumber"
                    value={formData.roomNumber}
                    onChange={handleInputChange}
                    min={101}
                    max={520}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Booking Amount ($)</label>
                  <input 
                    type="number" 
                    name="revenue"
                    value={formData.revenue}
                    onChange={handleInputChange}
                    min={1}
                    required
                  />
                </div>
              </div>

              <div className="form-group-row">
                <div className="form-group">
                  <label>Check-In Date</label>
                  <input 
                    type="date" 
                    name="checkIn"
                    value={formData.checkIn}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Check-Out Date</label>
                  <input 
                    type="date" 
                    name="checkOut"
                    value={formData.checkOut}
                    onChange={handleInputChange}
                    required
                  />
                </div>
              </div>

              <div className="form-group-row">
                <div className="form-group">
                  <label>Payment Method</label>
                  <select name="paymentMethod" value={formData.paymentMethod} onChange={handleInputChange}>
                    <option value="Credit Card">Credit Card</option>
                    <option value="PayPal">PayPal</option>
                    <option value="Cash">Cash</option>
                    <option value="Bank Transfer">Bank Transfer</option>
                  </select>
                </div>
              </div>

              <div className="email-disclaimer">
                <FiAlertCircle size={14} className="text-warning" />
                <p>Submitting this form will automatically launch a Gmail notifier populated for <strong>mirfurkaan106@gmail.com</strong>.</p>
              </div>

              <div className="form-actions-row">
                <button type="button" className="btn-secondary" onClick={() => setIsModalOpen(false)}>
                  Cancel
                </button>
                <button type="submit" className="btn-primary-action">
                  Confirm Booking
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Bookings;
export { Bookings };
